/* flashcards.js — the deck's home screen on the website.
 *
 * HAND-WRITTEN. Everything it imports from `./study/` is GENERATED by
 * Fiwo/Tools/build_web_study.mjs, vendored from the Android app so that a card
 * behaves identically on both surfaces and one test suite covers both. This
 * file is the website's own chrome around that engine — the app's `app.js` and
 * `cardsScreen.js` are its counterparts there, and are deliberately not shared:
 * the app has a tab bar and a native shell, this has a sidebar and a hash router.
 *
 * ── LOADED AS A MODULE ──────────────────────────────────────────────────────
 * The first ES module on the site. `script.js` is a classic script and runs
 * first, so it cannot call into here directly at parse time; the two meet at
 * `window.FiwoFlashcards`, which this file publishes and then immediately
 * checks whether the flashcards page is already showing (a deep link to
 * `#flashcards` resolves before this module has finished loading).
 *
 * ── WHAT IS HERE AND WHAT IS VENDORED ───────────────────────────────────────
 * This file owns the HOME screen: what is due, what you have met, the filters
 * you pick before starting, and the storage readout. The SESSION — the card,
 * the swipe, WASD, undo, the interval preview — is `study/js/study.js`, the
 * app's own screen running unchanged. Starting it is four lines at the bottom.
 */
import { buildCards, buildQueue, DEFAULT_STUDY_SETTINGS } from './study/js/deck.js';
import { emptyProgress, sanitizeProgress } from './study/js/cards.js';
import { dashboard, MATURE_DAYS } from './study/js/stats.js';
import { startSession, endSession } from './study/js/study.js';
import { attachTimekeeping, formatDuration, tracker } from './study/js/timer.js';

const CONTENT_URL = 'study-content.json';

const POS_ORDER = [
    'Biological Noun', 'Concrete Noun', 'Abstract Noun',
    'Verb', 'Modifier', 'Prepositions', 'Grammar',
];
const TIERS = [[0, 'Grammar core'], [1, 'Core'], [2, 'Extended'], [3, 'Long tail']];
const TIER_NAME = { 0: 'Grammar core', 1: 'Core', 2: 'Extended', 3: 'Long tail' };

let content = null;      // the bundle, once fetched
let allCards = null;     // buildCards(content), cached — 8,268 objects
let storyIdByTitle = null;
let loading = null;      // in-flight fetch, so a double navigation fetches once
let filters = null;
let settings = null;

const $ = (sel) => document.querySelector(sel);
const fmt = (n) => Number(n).toLocaleString('en');

function esc(s) {
    return String(s).replace(/[&<>"']/g, ch => (
        { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[ch]
    ));
}

/* ── The progress adapter ────────────────────────────────────────────────────
 *
 * The engine expects the app's progress object; the browser has FiwoStore.
 * The two agree on `cards` by design (same shape, same ids), so the only real
 * translation is stories: FiwoStore keys them by TITLE because that is what a
 * reader's URL and bookmark know, and the app keys them by the hashed id.
 *
 * The bundle carries both, so the map is a lookup rather than a SHA-1 — which
 * matters, because hashing in a browser is async and this runs on every render.
 */
function toAppProgress() {
    const p = emptyProgress();
    p.cards = FiwoStore.cards();
    p.time = FiwoStore.time();
    if (storyIdByTitle) {
        for (const [title, entry] of Object.entries(FiwoStore.stories())) {
            const id = storyIdByTitle.get(title);
            if (id) p.stories[id] = { read: entry.read, line: entry.line };
        }
    }
    // Sanitised for the same reason the app does it at boot: this data can
    // arrive from an imported file, an older build, or a hand edit, and the
    // dashboard is the first thing to touch every field of it.
    return sanitizeProgress(p).progress;
}

const countReviews = (cards) =>
    Object.values(cards || {}).reduce((n, c) => n + (c.reviews?.length || 0), 0);

/* The other direction. Only `cards` and `time` travel back: stories are DERIVED
 * from FiwoStore on the way in, and writing the engine's copy back would
 * translate titles to ids and then have nothing to translate them back with.
 *
 * How much NEW work this write contains is measured rather than asserted. The
 * session calls the same save callback after a grade and after an undo, so a
 * flag passed in by the caller counted undos as reviews — the backup nag then
 * claimed more unprotected work than existed. Cheap to measure: `cards` only
 * holds entries for cards actually studied, not all 8,268. */
function fromAppProgress(progress) {
    const added = countReviews(progress.cards) - countReviews(FiwoStore.cards());
    FiwoStore.setCards(progress.cards, Math.max(0, added));
    FiwoStore.setTime(progress.time || {});
}

/* ── Settings and filters, remembered ────────────────────────────────────────
 * Through FiwoStore.setPref so they persist and travel in an export, rather
 * than resetting every visit the way a module-level default would. */
function loadPrefs() {
    /* Copied on the way in as well: getPref hands back the stored object itself,
     * and toggleChip mutates these in place. Validated before copying, because a
     * pref restored from a hand-edited or older export can be any shape at all
     * and spreading a number throws. */
    const list = (key) => {
        const raw = FiwoStore.getPref(key, null);
        return Array.isArray(raw) ? [...raw] : [];
    };

    filters = { pos: list('deck.pos'), tiers: list('deck.tiers'), set: 'all', tags: [] };
    settings = {
        ...DEFAULT_STUDY_SETTINGS,
        newCardsPerDay: FiwoStore.getPref('deck.newPerDay', DEFAULT_STUDY_SETTINGS.newCardsPerDay),
        production: FiwoStore.getPref('deck.production', DEFAULT_STUDY_SETTINGS.production),
        sentences: FiwoStore.getPref('deck.sentences', DEFAULT_STUDY_SETTINGS.sentences),
    };
}

function savePrefs() {
    /* Copies, not the live arrays.
     *
     * `setPref` skips the write when the value is `===` what it already holds,
     * which is right for the scalars it was built for and wrong here: handing it
     * the same array back means every later toggle mutates the stored object in
     * place, the identity check passes, and NOTHING IS EVER PERSISTED AGAIN.
     * The filter would then survive exactly one change per session. */
    FiwoStore.setPref('deck.pos', [...filters.pos]);
    FiwoStore.setPref('deck.tiers', [...filters.tiers]);
    FiwoStore.setPref('deck.newPerDay', settings.newCardsPerDay);
    FiwoStore.setPref('deck.production', settings.production);
    FiwoStore.setPref('deck.sentences', settings.sentences);
}

// ── Loading ─────────────────────────────────────────────────────────────────

/* 1.4 MB, fetched on the first visit to this page and never on the site's
 * initial load. The service worker caches it on first use, the same treatment
 * stories.js and DerivedDictionary.js get. */
async function ensureContent() {
    if (content) return content;
    if (loading) return loading;
    loading = fetch(CONTENT_URL)
        .then(r => {
            if (!r.ok) throw new Error(`${r.status} ${r.statusText}`);
            return r.json();
        })
        .then(bundle => {
            content = bundle;
            allCards = buildCards(bundle);
            storyIdByTitle = new Map(bundle.stories.map(s => [s.title, s.id]));
            return bundle;
        })
        .finally(() => { loading = null; });
    return loading;
}

// ── Rendering ───────────────────────────────────────────────────────────────

const stat = (value, label, hint = '') => `
    <div class="fc-stat">
        <div class="fc-stat-value">${esc(String(value))}</div>
        <div class="fc-stat-label">${esc(label)}</div>
        ${hint ? `<div class="fc-stat-hint">${esc(hint)}</div>` : ''}
    </div>`;

function bar(label, value, total, cls, showTotal = false) {
    const pct = total ? Math.round((value / total) * 100) : 0;
    return `
    <div class="fc-bar-row">
        <div class="fc-bar-head">
            <span>${esc(label)}</span>
            <span class="fc-bar-val">${fmt(value)}${showTotal ? ` / ${fmt(total)}` : ''}</span>
        </div>
        <div class="fc-bar"><div class="fc-bar-fill ${cls}" style="width:${pct}%"></div></div>
    </div>`;
}

/* Five buckets rather than a linear scale, copied from the app's reasoning:
 * review counts are heavily skewed — one catch-up day dwarfs a month of steady
 * work — so a linear ramp renders almost every real day the same shade. */
function cell(c) {
    const level = c.count === 0 ? 0 : c.count < 5 ? 1 : c.count < 15 ? 2 : c.count < 40 ? 3 : 4;
    return `<i class="fc-heat-cell fc-heat-l${level}${c.future ? ' is-future' : ''}${c.isToday ? ' is-today' : ''}"
        title="${esc(c.date)}: ${c.count}"></i>`;
}

function chips(group, items, active) {
    return items.map(([value, label]) => `
        <button type="button" class="fc-chip${active.includes(value) ? ' is-on' : ''}"
            data-chip-group="${group}" data-chip-value="${esc(String(value))}"
            aria-pressed="${active.includes(value)}">${esc(label)}</button>`).join('');
}

function render() {
    const body = $('#flashcards-body');
    if (!body || !content) return;

    const progress = toAppProgress();
    const q = buildQueue(allCards, progress, filters, settings);
    const d = dashboard(content, allCards, progress);
    const seen = d.states.learning + d.states.young + d.states.mature;
    const started = d.totalReviews > 0;

    body.innerHTML = `
        <div class="fc-due ${q.queue.length ? '' : 'is-clear'}">
            ${q.queue.length ? `
                <div class="fc-due-main"><b>${fmt(q.dueCount)}</b> due · <b>${fmt(q.newCount)}</b> new</div>
                <div class="fc-due-note">Swipe to grade — up for Good, right for Easy, down for Again,
                left for Hard — or the same four on <kbd>W</kbd> <kbd>A</kbd> <kbd>S</kbd> <kbd>D</kbd>.</div>
                <button type="button" class="fc-start" data-fc-start>Study ${fmt(q.queue.length)} cards</button>
            ` : `
                <div class="fc-due-main">Nothing due</div>
                <div class="fc-due-note">${started
                    ? `All caught up.${d.time.today.cards ? ` ${formatDuration(d.time.today.cards)} of flashcards today.` : ''}`
                    : 'Pick what you want to study below, then come back.'}</div>
            `}
        </div>

        <div class="fc-stat-grid">
            ${(() => {
                /* ONE streak, shared with the workbook (roadmap D9). The
                 * vendored `stats.js` computes its own from card reviews and
                 * cannot see the workbook — it is the app's module and the app
                 * has no workbook. Two counters on one site disagreeing about
                 * whether you studied today teaches the reader to trust
                 * neither, so both surfaces read FiwoStore.streak(). */
                const s = FiwoStore.streak();
                return stat(s.current, 'day streak',
                    s.longest > s.current ? `best ${s.longest}` : (s.current && !s.today ? 'nothing today yet' : ''));
            })()}
            ${stat(`${fmt(seen)}`, 'cards started', `${fmt(d.states.new)} not yet seen`)}
        </div>

        ${d.totalReviews ? `
        <div class="fc-block">
            <h3>Last 13 weeks · ${fmt(d.totalReviews)} reviews</h3>
            <div class="fc-heat">${d.heatmap.map(cell).join('')}</div>
            <div class="fc-heat-key"><span>less</span>
                ${[0, 1, 2, 3, 4].map(l => `<i class="fc-heat-cell fc-heat-l${l}"></i>`).join('')}
                <span>more</span></div>
        </div>` : ''}

        ${seen ? `
        <div class="fc-block">
            <h3>Cards</h3>
            ${bar('Learning', d.states.learning, seen, 'grade-1')}
            ${bar('Young', d.states.young, seen, 'grade-3')}
            ${bar(`Mature (${MATURE_DAYS}d+)`, d.states.mature, seen, 'grade-4')}
        </div>` : ''}

        <div class="fc-block">
            <h3>Words met by tier</h3>
            ${d.tiers.map(t => bar(TIER_NAME[t.tier] || `Tier ${t.tier}`, t.seen, t.total, 'grade-3', true)).join('')}
            <p class="fc-note">Derived words have no tier of their own and count as
            Extended, the same way the deck treats them.</p>
        </div>

        <div class="fc-block">
            <h3>What to study</h3>
            <p class="fc-note">Nothing selected in a group means no restriction from it,
            so "just study what is due" stays one tap. Every card has one review history
            whichever way you reach it — these are filters over one deck, not separate decks.</p>

            <div class="fc-filter">
                <span class="fc-filter-label">Part of speech</span>
                <div class="fc-chips">${chips('pos', POS_ORDER.map(p => [p, p]), filters.pos)}</div>
            </div>
            <div class="fc-filter">
                <span class="fc-filter-label">Tier</span>
                <div class="fc-chips">${chips('tiers', TIERS, filters.tiers)}</div>
            </div>

            <div class="fc-filter">
                <span class="fc-filter-label">New cards a day</span>
                <input type="number" id="fc-new-per-day" class="fc-number" min="0" max="500"
                    value="${Number(settings.newCardsPerDay) || 0}">
            </div>
            <label class="fc-toggle">
                <input type="checkbox" id="fc-production" ${settings.production ? 'checked' : ''}>
                <span><b>English → Fiwo cards.</b> The direction that fails when you try to
                speak — recognising a word you invented tells you almost nothing.</span>
            </label>
            <label class="fc-toggle">
                <input type="checkbox" id="fc-sentences" ${settings.sentences ? 'checked' : ''}>
                <span><b>Whole sentences.</b> ${fmt(content.counts?.sentences ?? 0)} of them, off by
                default — useful once the words are solid, noise before that.</span>
            </label>
        </div>

        <div class="fc-block">
            <h3>Your progress</h3>
            <div id="flashcards-storage" class="storage-health"></div>
            <p class="fc-note">This deck uses the same card identities as the Fiwo
            phone app, so a progress file exported from one imports into the other.
            Export and import live on the <a href="#lets-read">Let's Read</a> page.</p>
        </div>

        <p class="fc-build">${fmt(content.counts?.words ?? 0)} words ·
        ${fmt(content.counts?.cards ?? 0)} cards · content ${esc(content.version || '—')}</p>`;

    // The same component the reader's progress panel uses (Layer 5). Mounted
    // here too because this is where the data worth protecting will live.
    if (typeof mountStorageHealth === 'function') {
        mountStorageHealth(document.getElementById('flashcards-storage'));
    }
}

function renderError(err) {
    const body = $('#flashcards-body');
    if (!body) return;
    body.innerHTML = `
        <div class="fc-block">
            <h3>The deck could not load</h3>
            <p class="fc-note">${esc(String(err && err.message || err))}</p>
            <p class="fc-note">The word list is a separate 1.4 MB file, fetched the first
            time you open this page. If you are offline and have not opened it before,
            it will not be in the cache yet.</p>
            <button type="button" class="progress-btn" data-fc-retry>Try again</button>
        </div>`;
}

// ── Wiring ──────────────────────────────────────────────────────────────────

function toggleChip(group, rawValue) {
    const list = filters[group];
    // Tier chips carry numbers; part-of-speech chips carry strings. The DOM
    // only ever hands back a string, so the tier group is coerced back — a
    // string '1' would never match `card.tier === 1` and the filter would
    // silently exclude everything.
    const value = group === 'tiers' ? Number(rawValue) : rawValue;
    const i = list.indexOf(value);
    if (i === -1) list.push(value); else list.splice(i, 1);
    savePrefs();
    render();
}

document.addEventListener('click', (e) => {
    const chip = e.target.closest('[data-chip-group]');
    if (chip) { toggleChip(chip.dataset.chipGroup, chip.dataset.chipValue); return; }
    if (e.target.closest('[data-fc-retry]')) { open(); return; }
    if (e.target.closest('[data-fc-start]')) { study(); }
});

/* ── The session ─────────────────────────────────────────────────────────────
 *
 * `startSession` is the app's own screen, vendored unchanged: it builds its own
 * full-screen element, owns the keyboard while it is up, and hands progress
 * back through the two callbacks. Everything below is plumbing.
 */
let sessionActive = false;

function study() {
    if (sessionActive || !content) return;
    const progress = toAppProgress();
    const { queue } = buildQueue(allCards, progress, filters, settings);
    if (!queue.length) return;

    sessionActive = true;
    // Same lock the reader uses. Without it the page behind a full-screen
    // overlay still scrolls, and a swipe that starts just off the card drags
    // the site around underneath it.
    document.body.classList.add('study-open');
    startSession(
        queue,
        progress,
        // Persist after EVERY grade. A session that loses its last ten reviews
        // to a closed tab is worse than one that writes a small object eleven
        // times — and unlike the app, a browser tab can vanish without warning.
        async (next) => fromAppProgress(next),
        // Runs on every exit path — ✕, Escape, Back, and finishing the queue —
        // because study.js routes all four through finish().
        (next) => {
            sessionActive = false;
            document.body.classList.remove('study-open');
            fromAppProgress(next);
            render();
        },
    );
}

/* Browser Back during a session would change the section underneath a
 * full-screen overlay, leaving you studying on top of the wrong page and
 * landing somewhere unexpected on exit. Treat it as "leave the session", which
 * is what pressing Back means. */
window.addEventListener('hashchange', () => {
    if (sessionActive) endSession();
});

document.addEventListener('change', (e) => {
    const t = e.target;
    if (t.id === 'fc-new-per-day') {
        const n = Math.max(0, Math.min(500, Number(t.value) || 0));
        settings.newCardsPerDay = n;
    } else if (t.id === 'fc-production') {
        settings.production = t.checked;
    } else if (t.id === 'fc-sentences') {
        settings.sentences = t.checked;
    } else return;
    savePrefs();
    render();
});

// Keeps the deck in step with everything else that writes progress — finishing
// a story on the reader moves the "stories read" figure here. Skipped during a
// session: the dashboard is behind a full-screen overlay, and re-rendering it
// after every grade is work nobody can see.
document.addEventListener('fiwo-store-changed', () => {
    if (content && !sessionActive) render();
});

/* Engaged-time tracking. The vendored timer counts only while the page is in
 * front of you AND you are still doing something, so a tab left open in another
 * window does not accrue hours of "study". Attached once, at module load,
 * because it installs document-level listeners that must not stack up.
 *
 * `persist` is where the tracker's in-memory totals get stamped into progress —
 * `applyTo` is not called anywhere else, so a persist that just writes what it
 * was handed records nothing at all. */
tracker.seed({ time: FiwoStore.time() });

attachTimekeeping({
    persist: async (progress) => FiwoStore.setTime(tracker.applyTo(progress).time || {}),
    getProgress: () => ({ time: FiwoStore.time() }),
    onChange: () => { if (content && !sessionActive) render(); },
});

/** Called by script.js when #flashcards becomes the active section. */
async function open() {
    const body = $('#flashcards-body');
    if (!body) return;
    if (!content) body.innerHTML = '<p class="fc-note">Loading the deck…</p>';
    try {
        loadPrefs();
        await ensureContent();
        render();
    } catch (err) {
        renderError(err);
    }
}

window.FiwoFlashcards = { open };

/* A deep link to #flashcards resolves during script.js evaluation, which
 * happens before this module finishes loading. So rather than relying on being
 * called, check on arrival whether the page is already showing. */
if (document.getElementById('flashcards')?.classList.contains('active')) open();
